
* Do que é esperado dos membros
  É esperado do membro que se sinta membro de fato, o que pode ser resumido nos seguintes itens

** Proatividade:
   - Viu que há algo que precisa ser feito? Faça.
** Comprometimento:
   - Disse que vai fazer algo? Os membros do grupo estão contando que você faça. Então faça da melhor forma que puder.
   - Compareça no horário marcado para as reuniões e eventos. Se não puder, justifique.
*** Este item em particular pode levar à retirada de um membro do grupo:
    - Na ocorrência de 3 faltas não justificadas plausivelmente, o membro é convidado a se retirar do grupo.
      Exemplos do que não são consideradas justificativas plausíveis:
      1. Prova no dia ou dia seguinte (estude antes);
      2. Ter que entregar trabalho (entregue antes);
      3. Estar chovendo.
      Exemplos do que são consideradas justificativas plausíveis:
      1. Houve um imprevisto logístico (como atraso de ônibus ou súbita alteração de horário por professor);
      2. Doença;
      3. Morte de entes queridos.
** Inovação:
   - Para o grupo crescer de forma saudável, é de grande importância que seus membros busquem melhorá-lo constantemente.
     Um olhar afiado ao que é preciso mudar (assim como ao que devemos começar a fazer ou deixar de fazer) é essencial.
** Crítica responsável:
   - É essencial saber criticar e saber ouvir. Críticas podem ser de grande ajuda para o crescimento pessoal de cada um e do grupo
     e devem ser pensadas e ditas com esse propósito, não com o de agressão.
     Da mesma forma, é importante que saibamos ouvir críticas e saber pesá-las quanto a seu fundamento de forma racional.

* Dos projetos
** Cineclube
   - Proposta:
     Reunião a cada 2 semanas para assistir a um filme escolhido por votação
     seguida de breve discussão sobre o filme
   - Motivação:
     Aumentar visibilidade do grupo na Universidade;
     Melhorar coesão dos membros com um evento integrador e (assim se espera) divertido;
   - Presença dos membros altamente recomendada, mas 
** Geometria de Jabutis (nome provisório)
   - Proposta:
     (em elaboração)
   - Motivação:
     (em elaboração)
